// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw7XYG2dO8sZf_J0rvUwfR4qjKIcxbT24',
    appId: '1:608191959933:web:2f158725dafbd3e34c3214',
    messagingSenderId: '608191959933',
    projectId: 'socialmediaapp-5ee9c',
    authDomain: 'socialmediaapp-5ee9c.firebaseapp.com',
    storageBucket: 'socialmediaapp-5ee9c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-I2l7R-7NH4T69wayrVxAm5BeXV_i374',
    appId: '1:608191959933:android:92ea110f3d5dde204c3214',
    messagingSenderId: '608191959933',
    projectId: 'socialmediaapp-5ee9c',
    storageBucket: 'socialmediaapp-5ee9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNHr2Rg17X49mDGO9bjJOWu5Tc49j-iYs',
    appId: '1:608191959933:ios:f90f87de2c41bc0d4c3214',
    messagingSenderId: '608191959933',
    projectId: 'socialmediaapp-5ee9c',
    storageBucket: 'socialmediaapp-5ee9c.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNHr2Rg17X49mDGO9bjJOWu5Tc49j-iYs',
    appId: '1:608191959933:ios:f90f87de2c41bc0d4c3214',
    messagingSenderId: '608191959933',
    projectId: 'socialmediaapp-5ee9c',
    storageBucket: 'socialmediaapp-5ee9c.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw7XYG2dO8sZf_J0rvUwfR4qjKIcxbT24',
    appId: '1:608191959933:web:156de9c2e94afccc4c3214',
    messagingSenderId: '608191959933',
    projectId: 'socialmediaapp-5ee9c',
    authDomain: 'socialmediaapp-5ee9c.firebaseapp.com',
    storageBucket: 'socialmediaapp-5ee9c.appspot.com',
  );
}
